# Generated by Django 3.1.3 on 2020-11-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20201110_0531'),
    ]

    operations = [

    ]
